name: Deploy static content to Github Pages

on:
  push:
    branches: docs

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build docs
        run: RUSTDOCFLAGS="--default-theme=ayu" cargo doc --document-private-items
      - name: Copy static assets
        run: cp docs/* target/doc
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'target/doc'
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
